import { ArrowLeft, CheckCircle, UsersRound, Factory, ShieldCheck, HardHat, Globe2, Settings2 } from "lucide-react";
import { Link } from "wouter";
import { useLanguage } from "@/contexts/LanguageContext";

const icons = { inserimento: UsersRound, produttive: Factory, sicurezza: ShieldCheck, cantieri: HardHat, intercultura: Globe2, misura: Settings2 } as const;
type ServiceKey = keyof typeof icons;

const content: Record<ServiceKey, Record<string, {title:string; intro:string; bullets:string[]; result:string}>> = {
  inserimento: {
    it:{title:"Italiano per l'inserimento in azienda",intro:"Un percorso per aiutare nuove risorse straniere a comprendere il contesto di lavoro, comunicare con il team e acquisire autonomia fin dai primi giorni.",bullets:["Lessico di base e presentazione personale","Istruzioni, routine e regole interne","Comunicazione con colleghi e responsabili","Intercultura e gestione delle incomprensioni"],result:"Più fiducia, autonomia e partecipazione nel gruppo di lavoro."},
    en:{title:"Italian for workplace onboarding",intro:"A path helping new international employees understand the workplace, communicate with the team and build autonomy from the first days.",bullets:["Core workplace vocabulary and introductions","Instructions, routines and internal rules","Communication with colleagues and supervisors","Intercultural awareness and misunderstandings"],result:"More confidence, autonomy and participation within the team."},
    fr:{title:"Italien pour l'intégration en entreprise",intro:"Un parcours pour aider les nouveaux salariés étrangers à comprendre le contexte de travail, communiquer avec l'équipe et gagner en autonomie dès les premiers jours.",bullets:["Vocabulaire professionnel de base et présentation","Consignes, routines et règles internes","Communication avec collègues et responsables","Interculturalité et gestion des incompréhensions"],result:"Plus de confiance, d'autonomie et de participation dans l'équipe."},
    ar:{title:"الإيطالية للاندماج في الشركة",intro:"مسار يساعد الموظفين الأجانب الجدد على فهم بيئة العمل والتواصل مع الفريق وبناء الاستقلالية منذ الأيام الأولى.",bullets:["المفردات الأساسية والتعريف بالنفس","التعليمات والروتين والقواعد الداخلية","التواصل مع الزملاء والمسؤولين","الوعي الثقافي وإدارة سوء الفهم"],result:"ثقة واستقلالية ومشاركة أكبر داخل فريق العمل."}
  },
  produttive: {
    it:{title:"Italiano per i reparti produttivi",intro:"Italiano L2 costruito sui ritmi e sulle comunicazioni reali di fabbrica, produzione, magazzino e logistica.",bullets:["Lessico tecnico di reparto","Istruzioni e sequenze di lavoro","Comunicazione con capi turno e colleghi","Segnalazioni, controlli e problemi pratici"],result:"Meno incomprensioni, più coordinamento, qualità e autonomia."},
    en:{title:"Italian for production teams",intro:"Italian L2 built around the real pace and communication needs of factories, production areas, warehouses and logistics.",bullets:["Technical workplace vocabulary","Instructions and work sequences","Communication with supervisors and colleagues","Reporting, checks and practical issues"],result:"Fewer misunderstandings, better coordination, quality and autonomy."},
    fr:{title:"Italien pour les équipes de production",intro:"Un italien L2 adapté aux rythmes et aux communications réelles de l'usine, de la production, des entrepôts et de la logistique.",bullets:["Vocabulaire technique du service","Consignes et séquences de travail","Communication avec chefs d'équipe et collègues","Signalements, contrôles et problèmes pratiques"],result:"Moins d'incompréhensions, plus de coordination, de qualité et d'autonomie."},
    ar:{title:"الإيطالية لأقسام الإنتاج",intro:"تعليم الإيطالية كلغة ثانية وفق إيقاع العمل والتواصل الحقيقي في المصانع والإنتاج والمخازن والخدمات اللوجستية.",bullets:["المفردات التقنية للقسم","التعليمات وتسلسل العمل","التواصل مع المشرفين والزملاء","الإبلاغ والفحوصات والمشكلات العملية"],result:"سوء فهم أقل وتنسيق وجودة واستقلالية أكبر."}
  },
  sicurezza: {
    it:{title:"Italiano per la sicurezza sul lavoro",intro:"Percorsi linguistici dedicati alla comprensione di segnaletica, procedure, DPI, emergenze e comunicazioni di prevenzione.",bullets:["Lessico della sicurezza","Cartelli, avvisi e simboli","DPI e procedure di emergenza","Istruzioni operative e comportamenti corretti"],result:"La sicurezza inizia dalla comprensione: meno ambiguità e maggiore consapevolezza."},
    en:{title:"Italian for workplace safety",intro:"Language paths focused on understanding signs, procedures, PPE, emergencies and prevention-related communication.",bullets:["Safety vocabulary","Signs, warnings and symbols","PPE and emergency procedures","Operational instructions and safe behaviours"],result:"Safety begins with understanding: less ambiguity and greater awareness."},
    fr:{title:"Italien pour la sécurité au travail",intro:"Des parcours linguistiques consacrés à la signalétique, aux procédures, aux EPI, aux urgences et aux communications de prévention.",bullets:["Vocabulaire de la sécurité","Panneaux, avertissements et symboles","EPI et procédures d'urgence","Consignes opérationnelles et comportements adaptés"],result:"La sécurité commence par la compréhension : moins d'ambiguïtés et plus de conscience."},
    ar:{title:"الإيطالية من أجل السلامة في العمل",intro:"مسارات لغوية لفهم الإشارات والإجراءات ومعدات الحماية والطوارئ ورسائل الوقاية.",bullets:["مفردات السلامة","اللافتات والتنبيهات والرموز","معدات الحماية وإجراءات الطوارئ","التعليمات والسلوكيات الصحيحة"],result:"السلامة تبدأ بالفهم: غموض أقل ووعي أكبر."}
  },
  cantieri: {
    it:{title:"Italiano nella gestione dei cantieri",intro:"Italiano L2 per contesti di cantiere, con attenzione a istruzioni, squadra, accessi, segnaletica e sicurezza.",bullets:["Lessico tecnico del cantiere","Ordini di servizio e indicazioni operative","Comunicazione con capisquadra e colleghi","Sicurezza, DPI e prevenzione delle incomprensioni"],result:"Più coordinamento sul campo e comunicazioni operative più chiare."},
    en:{title:"Italian for construction sites",intro:"Italian L2 for construction environments, focusing on instructions, teams, access, signage and safety.",bullets:["Construction-site vocabulary","Work orders and operational instructions","Communication with forepersons and colleagues","Safety, PPE and prevention of misunderstandings"],result:"Better field coordination and clearer operational communication."},
    fr:{title:"Italien pour les chantiers",intro:"Italien L2 pour les contextes de chantier, avec une attention aux consignes, aux équipes, aux accès, à la signalétique et à la sécurité.",bullets:["Vocabulaire technique du chantier","Ordres de service et consignes","Communication avec chefs d'équipe et collègues","Sécurité, EPI et prévention des incompréhensions"],result:"Plus de coordination sur le terrain et des communications plus claires."},
    ar:{title:"الإيطالية لإدارة مواقع البناء",intro:"الإيطالية كلغة ثانية لبيئات البناء مع التركيز على التعليمات والفرق والمداخل والإشارات والسلامة.",bullets:["المفردات التقنية لموقع البناء","أوامر العمل والتعليمات التشغيلية","التواصل مع رؤساء الفرق والزملاء","السلامة ومعدات الحماية والوقاية من سوء الفهم"],result:"تنسيق أفضل في الميدان وتواصل تشغيلي أوضح."}
  },
  intercultura: {
    it:{title:"Italiano per lavoratori stranieri e intercultura",intro:"Un percorso che unisce lingua e competenze interculturali per favorire comprensione reciproca, integrazione e collaborazione.",bullets:["Italiano per la vita lavorativa quotidiana","Comunicazione interculturale","Strategie per chiedere chiarimenti e segnalare difficoltà","Regole, ruoli e relazioni nel luogo di lavoro"],result:"Un ambiente più inclusivo, comprensibile e collaborativo."},
    en:{title:"Italian for international employees and intercultural communication",intro:"A path combining language and intercultural skills to support mutual understanding, inclusion and collaboration.",bullets:["Italian for everyday working life","Intercultural communication","Strategies for asking for clarification and raising concerns","Workplace rules, roles and relationships"],result:"A more inclusive, understandable and collaborative workplace."},
    fr:{title:"Italien pour salariés étrangers et interculturalité",intro:"Un parcours qui associe langue et compétences interculturelles pour favoriser la compréhension mutuelle, l'intégration et la collaboration.",bullets:["Italien pour la vie professionnelle quotidienne","Communication interculturelle","Stratégies pour demander des précisions et signaler les difficultés","Règles, rôles et relations au travail"],result:"Un environnement plus inclusif, clair et collaboratif."},
    ar:{title:"الإيطالية للعمال الأجانب والتواصل بين الثقافات",intro:"مسار يجمع بين اللغة والمهارات الثقافية لتعزيز الفهم المتبادل والاندماج والتعاون.",bullets:["الإيطالية للحياة المهنية اليومية","التواصل بين الثقافات","استراتيجيات طلب التوضيح والإبلاغ عن الصعوبات","القواعد والأدوار والعلاقات في مكان العمل"],result:"بيئة عمل أكثر شمولاً ووضوحاً وتعاوناً."}
  },
  misura: {
    it:{title:"Italiano per aziende su misura",intro:"Ogni impresa ha bisogni diversi. Il percorso nasce da un'analisi iniziale e viene costruito intorno a persone, reparti, turni e obiettivi.",bullets:["Analisi del bisogno linguistico","Programma e materiali personalizzati","Moduli brevi e operativi","Verifica dei progressi e obiettivi concreti"],result:"Una formazione coerente con il contesto reale dell'impresa."},
    en:{title:"Tailored Italian for companies",intro:"Every company has different needs. The path starts with an initial needs analysis and is built around people, teams, shifts and goals.",bullets:["Language-needs analysis","Tailored programme and materials","Short, practical modules","Progress checks and concrete goals"],result:"Training aligned with the company's real context."},
    fr:{title:"Italien sur mesure pour les entreprises",intro:"Chaque entreprise a des besoins différents. Le parcours commence par une analyse des besoins et s'adapte aux personnes, services, horaires et objectifs.",bullets:["Analyse des besoins linguistiques","Programme et supports personnalisés","Modules courts et opérationnels","Suivi des progrès et objectifs concrets"],result:"Une formation cohérente avec la réalité de l'entreprise."},
    ar:{title:"الإيطالية المخصصة للشركات",intro:"لكل شركة احتياجات مختلفة. يبدأ المسار بتحليل الاحتياجات ثم يُبنى وفق الأشخاص والأقسام والمناوبات والأهداف.",bullets:["تحليل الاحتياجات اللغوية","برنامج ومواد مخصصة","وحدات قصيرة وعملية","متابعة التقدم وأهداف واضحة"],result:"تدريب منسجم مع واقع الشركة."}
  }
};

export default function AziendaServizio({ service }: { service: ServiceKey }) {
  const { language } = useLanguage();
  const lang = language as "it"|"en"|"fr"|"ar";
  const data = content[service][lang] || content[service].it;
  const Icon = icons[service];
  const back = {it:"Torna alle aziende",en:"Back to companies",fr:"Retour aux entreprises",ar:"العودة إلى صفحة الشركات"}[lang];
  const cta = {it:"Parliamone",en:"Let's discuss it",fr:"Parlons-en",ar:"لنتحدث عن ذلك"}[lang];
  return <div className="min-h-screen bg-background" dir={lang === "ar" ? "rtl" : "ltr"}>
    <section className="py-12 md:py-20 bg-gradient-to-r from-[#3D4A2E] to-[#2D3A1E] text-white"><div className="container max-w-4xl"><Link href="/aziende"><a className="inline-flex items-center gap-2 text-white/80 hover:text-white font-bold mb-8"><ArrowLeft size={18}/>{back}</a></Link><div className="flex items-start gap-5"><div className="h-14 w-14 rounded-full bg-white/10 flex items-center justify-center shrink-0"><Icon size={28}/></div><div><h1 className="font-display text-4xl md:text-5xl font-bold">{data.title}</h1><p className="font-body text-lg text-white/80 mt-4 max-w-3xl">{data.intro}</p></div></div></div></section>
    <section className="py-16 md:py-24"><div className="container max-w-4xl"><h2 className="font-display text-3xl font-bold text-foreground mb-8">{lang === "it" ? "Il percorso" : lang === "en" ? "The path" : lang === "fr" ? "Le parcours" : "المسار"}</h2><div className="grid md:grid-cols-2 gap-5">{data.bullets.map((b,i)=><div key={i} className="p-6 rounded-2xl bg-white border border-border flex gap-3"><CheckCircle size={20} className="text-[#C4622D] shrink-0 mt-1"/><span className="font-body text-foreground/80">{b}</span></div>)}</div><div className="mt-10 p-7 rounded-2xl bg-[#F5EDD6] border-l-4 border-[#C4622D]"><p className="font-display text-2xl font-bold text-[#3D4A2E]">{data.result}</p></div><div className="text-center mt-10"><a href="/#contatti" className="inline-flex px-7 py-3 bg-[#C4622D] text-white font-body font-bold rounded-sm hover:bg-[#9E4E24]">{cta}</a></div></div></section>
  </div>;
}
