import { Link } from "wouter";
import { ArrowRight, CheckCircle } from "lucide-react";
import { useTranslation } from "@/hooks/useTranslation";

export default function ItalianoPeAziende() {
  const { t, language } = useTranslation();
  const rtl = language === "ar";
  const company = (t("aziendePage.company") as unknown) as string[];
  const employee = (t("aziendePage.employee") as unknown) as string[];
  // getTranslation returns arrays as objects; use the localized fallback below for safety.
  const localized = {
    it: { company:["Ridurre gli errori dovuti a incomprensioni linguistiche.","Aumentare l'autonomia operativa.","Rafforzare sicurezza e prevenzione.","Migliorare la collaborazione tra reparti.","Sostenere inclusione e organizzazione."], employee:["Più sicurezza nella comunicazione quotidiana.","Maggiore fiducia con colleghi e responsabili.","Migliore comprensione di regole e procedure.","Più opportunità di crescita professionale.","Maggiore integrazione nel gruppo di lavoro."]},
    en: { company:["Reduce errors caused by language misunderstandings.","Increase operational autonomy.","Strengthen safety and prevention.","Improve cooperation between teams.","Support inclusion and organisation."], employee:["Greater confidence in everyday communication.","More confidence with colleagues and supervisors.","Better understanding of rules and procedures.","More opportunities for professional growth.","Stronger integration into the team."]},
    fr: { company:["Réduire les erreurs liées aux incompréhensions linguistiques.","Renforcer l'autonomie opérationnelle.","Soutenir la sécurité et la prévention.","Améliorer la coopération entre équipes.","Favoriser l'inclusion et l'organisation."], employee:["Plus d'assurance dans la communication quotidienne.","Davantage de confiance avec collègues et responsables.","Meilleure compréhension des règles et procédures.","Plus d'opportunités d'évolution professionnelle.","Meilleure intégration dans l'équipe."]},
    ar: { company:["تقليل الأخطاء الناتجة عن سوء الفهم اللغوي.","زيادة الاستقلالية في العمل.","تعزيز السلامة والوقاية.","تحسين التعاون بين الأقسام.","دعم الاندماج والتنظيم."], employee:["ثقة أكبر في التواصل اليومي.","ثقة أكبر مع الزملاء والمسؤولين.","فهم أفضل للقواعد والإجراءات.","فرص أكبر للنمو المهني.","اندماج أقوى في فريق العمل."]}
  }[language] || { company, employee };
  return <div className="min-h-screen bg-background" dir={rtl ? "rtl" : "ltr"}>
    <section className="py-16 md:py-24 bg-gradient-to-r from-[#C4622D] to-[#D97B4A]"><div className="container max-w-4xl"><h1 className="font-display text-4xl md:text-5xl font-bold text-white mb-4">{t("aziende.title")}</h1><p className="font-body text-lg text-white/90">{t("aziende.subtitle")}</p></div></section>
    <section className="py-16 md:py-24"><div className="container max-w-4xl"><p className="font-body text-lg text-foreground/80 leading-relaxed">{t("aziendePage.intro")}</p></div></section>
    <section className="py-16 md:py-24 bg-muted/50"><div className="container max-w-5xl"><h2 className="font-display text-3xl md:text-4xl font-bold text-foreground mb-10">{t("aziendePage.whyTitle")}</h2><div className="grid md:grid-cols-2 gap-8"><div className="bg-white rounded-2xl p-7 border border-border"><h3 className="font-display text-2xl font-bold mb-5">{t("aziendePage.companyTitle")}</h3><ul className="space-y-3">{localized.company.map((x,i)=><li key={i} className="flex gap-3"><CheckCircle size={19} className="text-[#C4622D] shrink-0 mt-1"/><span>{x}</span></li>)}</ul></div><div className="bg-white rounded-2xl p-7 border border-border"><h3 className="font-display text-2xl font-bold mb-5">{t("aziendePage.employeeTitle")}</h3><ul className="space-y-3">{localized.employee.map((x,i)=><li key={i} className="flex gap-3"><CheckCircle size={19} className="text-[#C4622D] shrink-0 mt-1"/><span>{x}</span></li>)}</ul></div></div></div></section>
    <section className="py-16 md:py-24"><div className="container max-w-4xl"><h2 className="font-display text-3xl md:text-4xl font-bold mb-6">{t("aziendePage.concreteTitle")}</h2><p className="font-body text-lg text-foreground/80 leading-relaxed mb-8">{t("aziendePage.concreteText")}</p><Link href="/proposte"><a className="inline-flex items-center gap-2 text-[#C4622D] font-bold">{t("proposals.view")} <ArrowRight size={18}/></a></Link></div></section>
    <section className="py-16 md:py-24 bg-[#EEF2E8]"><div className="container max-w-4xl"><h2 className="font-display text-3xl md:text-4xl font-bold text-[#3D4A2E] mb-6">{t("aziendePage.strategicTitle")}</h2><p className="font-body text-lg text-[#3D4A2E]/80 leading-relaxed">{t("aziendePage.strategicText")}</p></div></section>
    <section className="py-16 md:py-24 bg-[#F5EDD6]"><div className="container max-w-3xl text-center"><h2 className="font-display text-3xl md:text-4xl font-bold text-[#3D4A2E] mb-4">{t("aziendePage.ctaTitle")}</h2><p className="font-body text-lg text-[#3D4A2E]/75 mb-8">{t("aziendePage.ctaText")}</p><a href="/#contatti" className="inline-flex px-6 py-3 bg-[#C4622D] text-white font-body font-bold rounded-sm">{t("aziendePage.cta")}</a></div></section>
  </div>;
}
